name: Deploy

on:
  push:
    tags: 'v*'
    branches: '*'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm ci-checks
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
